name = "kysely-d1"
main = "src/index.ts"
compatibility_date = "2023-02-03"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "kysely-test"
database_id = "6ad59e23-aa88-4040-859d-016031bf1426"
